language: python

sudo: false

python:
  - "2.7"
  - "3.6"

notifications:
  email:
    on_failure: change # [always|never|change] default: always
  flowdock:
    secure: d32tzqLnUIJge2QyAMtseJWf0yRb3LenW77xzEGVUD+abzlTtoCBbQBIRaWjJn3V78wd3ogLinplnMnu46tsQi7Q2XWiKaxrWq2ZPVfVCbV88whFiYMmmwnj6DNJjl3CxfGQXgui/VyPg9fyaDp5TyZfNZa/gEdedkn1J5kIF3g=


install:
  - SITE_PACKAGES=`pip --version | cut -d ' ' -f 4`
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a
  - conda create -q -n holoviews python=$TRAVIS_PYTHON_VERSION
  - travis_wait conda env update -n holoviews -q -f environment.yml
  - source activate holoviews
  - python setup.py develop
  - conda env export
  - if [ "$TRAVIS_PULL_REQUEST" == 'false' ]; then
      echo "Attempting to find any associated pull request";
      CURRENT_BUILD=$(curl -s -X GET "https://api.travis-ci.org/repos/ioam/holoviews/builds?number=$TRAVIS_BUILD_NUMBER");
      NEXT_BUILD=$(curl -s -X GET "https://api.travis-ci.org/repos/ioam/holoviews/builds?number=$((TRAVIS_BUILD_NUMBER + 1))");
      MSG1=$(echo $CURRENT_BUILD | jq '.[].message' );
      MSG2=$(echo $NEXT_BUILD | jq '.[].message' );
      if [ "$MSG1" == "$MSG2" ] ; then
        BUILD_ID=$(echo $NEXT_BUILD | jq .[].id);
        TRAVIS_PULL_REQUEST=$(curl -s -X GET "https://api.travis-ci.org/repos/ioam/holoviews/builds/$BUILD_ID" | jq .compare_url | cut -d '/' -f7 | cut -d \" -f1);
        echo "Associated pull request found - PR $TRAVIS_PULL_REQUEST";
      fi
    fi
  - REF_DATA_BRANCH=${TRAVIS_PULL_REQUEST//false/reference_data}
  - git clone https://github.com/ioam/holoviews-data.git -b reference_data ./doc/reference_data
  - cd ./doc/reference_data
  - echo "Attempting to checkout $REF_DATA_BRANCH branch"
  - if [ $(git branch -a --list *origin/$REF_DATA_BRANCH | wc -l) -eq 1 ] ; then
      git checkout origin/$REF_DATA_BRANCH;
    else
      echo "Using the master branch reference data";
    fi
  - cd ../..

before-script:
  - "echo 'backend : Agg' > $HOME/.matplotlib/matplotlibrc"

script:
  - export HOLOVIEWSRC=`pwd`'/holoviews.rc'
  - echo 'import holoviews as hv;hv.config(style_17=True);hv.config.warn_options_call=True' > holoviews.rc
  - flake8 --ignore=E,W,F999,F405 holoviews
  - nosetests --with-doctest --with-coverage --cover-package=holoviews
  - cd doc/nbpublisher; chmod +x test_notebooks.py; QT_QPA_PLATFORM='offscreen' BOKEH_DEV=True ./test_notebooks.py
  - chmod +x concat_html.py; ./concat_html.py ../test_data ../test_html
  - cd ../../; mv doc/Tutorials/.coverage ./.coverage.notebooks
  - coverage combine --append

after_script:
  - shopt -s expand_aliases
  - alias decode="tr '[N-ZA-Mn-za-m]' '[A-Za-z]'"
  - export AWS_SECRET_ACCESS_KEY=`echo udgGztmYyyKZ5iP2PVe+ROGZo/TI0M2QcoafOJGD | decode`
  - export AWS_ACCESS_KEY_ID=`echo NXVNVUCXF3UPHSKNG7ND | decode`
  - if [ "$TRAVIS_BRANCH" == 'master' ]; then
      cd doc/test_data;
      zip -r test_data.zip *;
      aws s3 cp --region eu-west-1 ./test_data.zip "s3://preview.holoviews.org/$TRAVIS_BUILD_NUMBER/test_data_py${TRAVIS_PYTHON_VERSION:0:1}.zip";
      cd -;
    fi
  - aws s3 cp --recursive --region eu-west-1 ./doc/test_html "s3://travis.holoviews.org/build_$TRAVIS_BUILD_NUMBER"
  - curl -s -X GET "https://kq5y73i0xe.execute-api.eu-west-1.amazonaws.com/dev/travis-holoviews-index"
  - echo insecure >> ~/.curlrc
  - if [ "$TRAVIS_PULL_REQUEST" != 'false' ]; then
      curl -X POST -d "$TRAVIS_BUILD_NUMBER" "https://kq5y73i0xe.execute-api.eu-west-1.amazonaws.com/dev/pr-status";
    fi

after_success: coveralls
