name: holoviews

channels:
  - conda-forge

dependencies:
  - pyviz::holoviews=0.9.*
  # Install requires
  - pyviz::param>=1.8.0,<2.0
  - pyviz::pyviz_comms>=0.7.2
  - pyviz::panel>=0.7.0
  - numpy>=1.0
  - pandas
  # Notebook dependencies already filled by binder
  # Recommended installs
  - matplotlib>=2.1
  - bokeh>=1.1.0
  # To run all examples
  - networkx
  - pillow
  - xarray>=0.10.4
  - plotly>=4.0
  - pyviz::datashader
  - selenium
  - phantomjs
  - ffmpeg
  - streamz>=0.5.0
  - cftime
  - netcdf4
  - bzip2
  - dask
  - scipy
