name: holoviews

channels:
  - conda-forge

dependencies:
  - defaults::numpy
  - defaults::scipy
  - defaults::matplotlib
  - defaults::ffmpeg
  - notebook
  - pillow
  - networkx
  - selenium
  - cyordereddict
  - phantomjs
  - pandas=0.24.0
  - xarray=0.11.0
  - ipython=5.4.1
  - jsonschema=2.6.0
  - nbconvert=5.3.1
  - netcdf4=1.3.1
  - flexx=0.4.1
  - plotly=3.4
  - bokeh=1.0.4
  - pyviz::param=1.8.1
  - pyviz::pyviz_comms=0.7.0
  - pyviz::datashader
  # Testing requirements
  - flake8
  - nose
  - path.py
  - deepdiff
  - awscli
  - coveralls
