name: holoviews

channels:
  - conda-forge

dependencies:
  - python=3.9
  - holoviews==1.15.3
  # Notebook dependencies already installed by binder
  # Recommended installs
  - matplotlib>=2.2
  - bokeh>=2.4.0,<3.0
  # To run all the examples
  - spatialpandas
  - networkx
  - pillow
  - xarray>=0.10.4
  - plotly>=4.0
  - datashader
  - selenium
  - phantomjs
  - ffmpeg
  - streamz>=0.5.0
  - cftime
  - netcdf4
  - bzip2
  - dask
  - scipy
  - ibis-sqlite >= 1.3
